http:
  port: ${PORT}
admin:
  port: ${ADMINPORT}
  host: ${ADMINHOST}
apiEndpoints:
  user:
    paths: /users/*
  razorpay:
    paths: /payments/*
  product:
    paths: /products/*
  invoice:
    paths: /invoices/*
  customerCare:
    paths: /chat/*
serviceEndpoints:
  user-service:
    url: ${USER_SERVICE_URL}
  razorpay-service:
    url: ${RAZORPAY_SERVICE_URL}
  product-service:
    url: ${PRODUCT_SERVICE_URL}
  invoice-service:
    url: ${INVOICE_SERVICE_URL}
  customerCare-service:
    url: ${CUSTOMERCARE_SERVICE_URL}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - user
      - razorpay
      - product
      - invoice
      - customerCare
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-service

  razorpayPipeline:
    apiEndpoints:
      - razorpay
    policies:
      - proxy:
          - action:
              serviceEndpoint: razorpay-service

  productPipeline:
    apiEndpoints:
      - product
    policies:
      - proxy:
          - action:
              serviceEndpoint: product-service

  invoicePipeline:
    apiEndpoints:
      - invoice
    policies:
      - proxy:
          - action:
              serviceEndpoint: invoice-service

  customerCarePipeline:
    apiEndpoints:
      - customerCare
    policies:
      - proxy:
          - action:
              serviceEndpoint: customerCare-service
